name: randyjhunt
favicon: null
layout_spectrum: 0.8586615754757077
typography_spectrum: 0.5869712987914681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5595249817706645
  lightness: 0.8099437591154128
  saturation: 0.7487413135822862
  rhythmicContrast: 0.12433914630673826
purpose: []
